### ISSUE TITLE
Espace sequences instead of cursor movement

### ISSUE THREAD

**Issue by rien333** [fabianishere/brainfuck#41]
I'm not sure if this intentional but the interpreter disallows basically any sort of cursor movement, like that with the arrow keys or emacs-like Ctrl-e/Ctrl-a type of stuff. When I try to to for example move my cursor to the right some escape sequence appears on the prompt instead. Any fix on my side or a rationale behind the choice to disable cursor movement ? (macOS 10.12 + iTerm)

**Comment by fabianishere** [comment]
Hi, the reason escape characters currently do not work in the interactive mode is that its implementation is really basic (20 lines of code) and therefore does not support movement of the cursor.

There is really no rationale behind this choice other than that I haven't had the time to implement it (plus probably needing a dependency like `readline` to handle input).

**Comment by rien333** [comment]
Hm, okay. Maybe I will try to implement it one day. Would you be open for that? And would it be okay to use the `readline` to achieve cursor movement?

**Comment by fabianishere** [comment]
Yes, of course!  Although, using `readline` might be an issue due to its incompatibility with our license (GPL vs Apache), but we could use a replacement like [editline](http://thrysoee.dk/editline/) to archieve the same functionality.

**Comment by fabianishere** [comment]
Fixed in #42
