### ISSUE TITLE
Build fails due to editline

### ISSUE THREAD

**Issue by eeerrrttty** [fabianishere/brainfuck#67]
[ 33%] Built target brainfuck
[ 50%] Building C object CMakeFiles/brainfuck-cli.dir/src/main.c.o
/home/romario/super-ia-project/bfinterpreter2/src/main.c:23:11: fatal error: editline/readline.h: No such file or directory
  #include <editline/readline.h>
           ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/brainfuck-cli.dir/build.make:62: recipe for target 'CMakeFiles/brainfuck-cli.dir/src/main.c.o' failed
make[2]: *** [CMakeFiles/brainfuck-cli.dir/src/main.c.o] Error 1
CMakeFiles/Makefile2:904: recipe for target 'CMakeFiles/brainfuck-cli.dir/all' failed
make[1]: *** [CMakeFiles/brainfuck-cli.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rien333** [comment]
Well, do you have the appropriate  library installed?

**Comment by eeerrrttty** [comment]
And now?!

**Comment by fabianishere** [comment]
@eeerrrttty Have you tried to install `editline` on your machine?

**Comment by eeerrrttty** [comment]
I'll try

**Comment by rien333** [comment]
@eeerrrttty What OS are you on? It's pretty easy to figure out how to install it from that point

**Comment by eeerrrttty** [comment]
Ubuntu 18. Resolved after editline install

**Comment by eeerrrttty** [comment]
Put sudo apt-get install libedit-dev as a dependency on readme instructions

**Comment by rien333** [comment]
@eeerrrttty from the README:

> Brainfuck requires CMake and a C compiler (e.g. Clang or GCC) in order to run. It _also depends_ on libedit, which is available in the main repositories of most Linux distributions (e.g. as [libedit-dev](https://packages.debian.org/stretch/libedit-dev) on Debian) and comes with the macOS XCode command line tools.

The fact that you need to `sudo apt-get install libedit-dev` is already implied by the fact that the Debian package is named `libedit-dev` (I suppose you are on Ubuntu, which is more or less a Debian derivative). 

That said, it might be nice to have installation instructions for different OSe, or, alternatively just package this interpreter for distros.

**Comment by fabianishere** [comment]
Fixed in #70.
