### ISSUE TITLE
Unexpected "error: tape memory out of bounds (overrun)"

### ISSUE THREAD

**Issue by radarek** [fabianishere/brainfuck#77]
I've run into some issue when playing with bf using this interpreter. Below is the simplest test case I was able to make, that show the problem:

```bf
>
><<
```

```bash
$ echo ">\n><<" | brainfuck
error: tape memory out of bounds (overrun)
exceeded the tape size of 30000 cells
$ echo $?
1
```

If we add single space between `>` and `<` then problem disappears:

```bf
>
> <<
```

```bash
$ echo ">\n> <<" | brainfuck
$ echo $?
0
```

**Comment by fabianishere** [comment]
Thank you for reporting the issue. I have confirmed that this is indeed an issue.

167b2de should resolve the issue.

**Comment by radarek** [comment]
Thanks for resolving the issue so quickly. I will check it in a free time.

**Comment by radarek** [comment]
I confirm that problem is resolved. Are you going to make a new release soon?

**Comment by fabianishere** [comment]
@radarek Thanks for reminding me! I have just published a new release: https://github.com/fabianishere/brainfuck/releases/tag/2.7.2

Let's see how quick downstream can catch up :)
