### ISSUE TITLE
 brainfuck.h not found during compilation

### ISSUE THREAD

**Issue by Privanom** [fabianishere/brainfuck#80]
`brainfuck.c:23:10: fatal error: brainfuck.h: No suck file or directory`
`main.c::34:10: fatal error: brainfuck.h: No such file or directory`

It seems that you need to include the full directory path
Edit: follow the steps in https://github.com/fabianishere/brainfuck#building

**Comment by fabianishere** [comment]
Could you outline the steps you took to reach these errors?

**Comment by Privanom** [comment]
> Could you outline the steps you took to reach these errors?

I `cd`'d into brainfuck/src, and typed `sudo gcc *.c`.

**Comment by fabianishere** [comment]
Please follow the build steps detailed in the [README](https://github.com/fabianishere/brainfuck#building). You'll need CMake to build this project.

**Comment by Privanom** [comment]
> Please follow the build steps detailed in the [README](https://github.com/fabianishere/brainfuck#building). You'll need CMake to build this project.

Oh, ok. My mistake
