### ISSUE TITLE
Have a look at this

### ISSUE THREAD

**Issue by elliot-zzh** [fabianishere/brainfuck#82]
This is not an issue.
I admire this project quite much, but please excuse me if I advertise my project here.
A visual brainfuck interpreter online:
Github Page: [web page](https://zhangzheheng12345.github.io/visual-brainfuck-web)
Github Repo: [v-bf-web](https://github.com/zhangzheheng12345/visual-brainfuck-web)

**Comment by fabianishere** [comment]
Hi, nice project, but I prefer to keep the issue tracker strictly for issues only.
