### ISSUE TITLE
Support for Windows ? And other things...

### ISSUE THREAD

**Issue by foxypiratecove37350** [fabianishere/brainfuck#84]
Is Windows supported ? Can you create a compiler fonctionality with this command scheme : `brainfuck <INPUT_FILE_PATH> -o <OUTPUT_FILE_PATH>` ? And can you create a distribuable installer in `.exe` for Windows (if Windows is supported), `.deb`/`.rpm` for Linux and `.dmg` for macOS ?

**Comment by fabianishere** [comment]
This repository contains a Brainfuck interpreter and not a compiler. It will execute Brainfuck instructions directly instead of compiling into a binary.

**Comment by foxypiratecove37350** [comment]
But you can add a compiling functionality, the name of the reposotory is `brainfuck`, not `brainfuck-interpreter`. If you want I can try to develop this functionality. And you didn't answer my question if Windows is supported, and you didn't talk about my idea of an installer file for users and not just source code for contributors.

**Comment by fabianishere** [comment]
1. At the moment, I have no plans to extend this project with a compiler. There exist quite a few Brainfuck compilers, I recommend taking a look at those. However, feel free to build something yourself if you are interested in that :)
2. Yes, Windows, Mac, and Linux are supported.
3. I have not yet worked on packaging the binary, #72 is tracking this, though you may find that others have packaged the project already for some platforms. I am happy to accept contributions for this.

**Comment by foxypiratecove37350** [comment]
Can you explain in details the steps for Windows build and installation ?

**Comment by foxypiratecove37350** [comment]
Why the dislike ?
